### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ijdtm7** [Maiq-The-Dude/PortableItemSpawner#1]
I have this all installed, I go into a sandbox scene but when i bring out the options panel its just the options panel, not the item spawner too.

**Comment by Maiq-The-Dude** [comment]
What scene/map specifically? I'll take a look and see what's going on.

**Comment by Ijdtm7** [comment]
I’ve tried many sandbox scenes, the main ones I use are proving grounds and friendly 45

**Comment by Maiq-The-Dude** [comment]
I just ran those yesterday with no issue. Can you provide your log file? Thanks

**Comment by Ijdtm7** [comment]
Where can I find the log file. I’ll be on my computer in 4 or 5 hours

**Comment by Maiq-The-Dude** [comment]
It will be under `H3VR/BepInEx/LogOutput.log`

**Comment by Ijdtm7** [comment]
Alright cool I’ll make sure I get it to you. I do have quite a bit of mods but even before installing those it was still not working

**Comment by Ijdtm7** [comment]
[LogOutput.log](https://github.com/Maiq-The-Dude/PortableItemSpawner/files/6380267/LogOutput.log)
alright here it is, ill be online for around 5  more hours if you require more

**Comment by Maiq-The-Dude** [comment]
`[Error  :      Deli] Failed to create mod from zip mod at 2Fort-Legacy.deli`

Another mod is throwing this error, could you delete the file here `h3vr/deli/mods/2Fort-Legacy.deli` and give it another go? If it still doesn't work then upload the same file again, it should have some new data.

Another thing to note is the portable itemspawner spawns ~0.5-1m in front of wherever the camera is pointing. So if you are sitting on the floor and looking down when spawning it it may be spawning underneath the floor.

**Comment by Ijdtm7** [comment]
alright let me try

**Comment by Ijdtm7** [comment]
[LogOutput.log](https://github.com/Maiq-The-Dude/PortableItemSpawner/files/6380589/LogOutput.log)
heres the new log
still doesnt work
when I spawn in the options panel when looking forward its just the options panel that spawns

**Comment by Maiq-The-Dude** [comment]
Hmm, the log appears as if everything is well. I guess what scene did you specifically test when you generated this log file? I know previously you mentioned you tried multiple scenes, but just trying to nail down your exact test scenario to see if I can replicate.

Also, can you go to `h3vr/bepinex/config/bepinex.cfg` and change these two settings under the `[Logging.Disk]` header, retry your test scenario and reupload the new log file? BepInEx doesn't seem to include some key data by default.
![image](https://user-images.githubusercontent.com/18471731/116288043-b58ee900-a756-11eb-8e57-7fdc804cac42.png)

**Comment by Ijdtm7** [comment]
Here’s what I do, I load up proving ground and look forward and also up while spawning options panel. I can get that other log to you tommorow

**Comment by Ijdtm7** [comment]
aight i got the new log, heres what i did, go into proving grounds, spawn options panel twice,fire the big boomer a few times, then spawn options panel again. Already getting a null pointer when the options panel gets spawned and portable item spawner is in the stacktrace, heres the log
[LogOutput.log](https://github.com/Maiq-The-Dude/PortableItemSpawner/files/6395157/LogOutput.log)

**Comment by Maiq-The-Dude** [comment]
I'll try to see if I can replicate this upcoming weekend. I think it is failing to get the options panel prefab but hard to tell and I'm not quite sure how it would fail there. At least we finally got some logging data to go off of, thanks a bunch.

**Comment by Maiq-The-Dude** [comment]
If you were up for it, would you mind giving the new 1.1.0 version a go next time you play H3VR? It requires a new dependency (Deli.H3VR) that has standardized the way to create panels that should fix the issue you were having before. Thanks

**Comment by Ijdtm7** [comment]
ok i can sunday what is deli.h3vr, is that just deli 0.3.2? or smth else

**Comment by Ijdtm7** [comment]
nvm i found it, will test again sunday

**Comment by Ijdtm7** [comment]
it works! thank you so much for fixing it!
